### ISSUE TITLE
此程序和v2rayN应用冲突

### ISSUE THREAD

**Issue by JoeZhangYN** [superDMS/HsFreezer-Hidden-in-the-snow-#24]
系统环境：win11 23H2 22631.3810
问题：假如不开软件，v2rayN.exe基本可以全程稳定运行。自从看了简介之后下载了这个软件，随后对一些常用的下载软件进行冻结。然而隔段时间，v2rayN.exe会在后台直接闪退，单从v2rayN的guiLogs日志中无任何记录。系统日志反馈如下：

.NET Runtime 报错：

Application: v2rayN.exe
CoreCLR Version: 8.0.624.26715
.NET Version: 8.0.6
Description: The application requested process termination through System.Environment.FailFast.
Message: 不可恢复的系统错误。
Stack:
   at System.Environment.FailFast(System.String)
   at System.Windows.Controls.TextBoxView.ArrangeVisuals(System.Windows.Size)
   at System.Windows.Controls.TextBoxView.ArrangeOverride(System.Windows.Size)
   at System.Windows.FrameworkElement.ArrangeCore(System.Windows.Rect)
   at System.Windows.UIElement.Arrange(System.Windows.Rect)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at v2rayN.App.Main()

应用程序报错：

错误应用程序名称: v2rayN.exe，版本: 6.45.0.0，时间戳: 0x661f0000
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0x80131623
错误偏移量: 0x00007ffb6118e13b
错误进程 ID: 0x0x107B0
错误应用程序启动时间: 0x0x1DACBC66E5BB9D5
错误应用程序路径: C:\temp\v2rayN-With-Core\v2rayN.exe
错误模块路径: unknown
报告 ID: 45f407a4-3626-45bb-9a56-fccf4da19f84
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by JoeZhangYN** [comment]
写了个程序10秒检测，不存在则重启，自己用着还行。
https://github.com/JoeZhangYN/KeepAPPAlive

**Comment by superDMS** [comment]
这个日志暂时看不出是哪个环节导致 问题    网站继续观察!谢谢反馈
